[tool.poetry]
name = "produt_maneger"
version = "0.1.0"
description = ""
authors = ["Flavio, Kaua"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
